#!/usr/bin/env python3
"""Fit the final linear QE model and emit JSON plus a constexpr C++ header."""
import argparse
import gzip
import glob
import json
import os

import numpy as np

import stats
from p6_learnability import (LAMBDA_RIDGE, NUM_FEATURES, feature_matrix,
                             row_examples)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="+")
    parser.add_argument("--json", required=True)
    parser.add_argument("--header", required=True)
    parser.add_argument("--lambda", dest="lambda_", type=float, default=2.0)
    args = parser.parse_args()
    files = []
    for path in args.paths:
        files.extend(sorted(glob.glob(os.path.join(path, "*.jsonl.gz")))) \
            if os.path.isdir(path) else files.append(path)
    rows = []
    for path in files:
        with gzip.open(path, "rt") as fh:
            for line in fh:
                if not line.strip():
                    continue
                row = json.loads(line)
                if row.get("type") == "decision":
                    rows.append(row)
    examples = [e for row in rows for e in row_examples(row)]
    X, scale = feature_matrix(examples)
    q = np.array([e[2] for e in examples], dtype=np.float64)
    log_cost = np.log(np.maximum(np.array([e[3] for e in examples]), 1.0))
    wq, bq, _, _ = stats.irls_logistic(X[:, :-1], q, lam=LAMBDA_RIDGE,
                                       penalize_intercept=True, tol=1e-8,
                                       max_iter=40)
    wc, bc = stats.ridge_fit(X[:, :-1], log_cost, lam=LAMBDA_RIDGE,
                             penalize_intercept=True)
    p1, p99, mu, sd = scale
    model = {"schema": "linear-qe-model/1", "features": NUM_FEATURES,
             "lambda": args.lambda_, "training_rows": len(rows),
             "training_examples": len(examples),
             "p1": p1.tolist(), "p99": p99.tolist(), "mean": mu.tolist(),
             "sd": sd.tolist(), "q_coef": wq.tolist(), "q_intercept": bq,
             "cost_coef": wc.tolist(), "cost_intercept": bc,
             "source_files": [os.path.basename(f) for f in files]}
    with open(args.json, "w") as fh:
        json.dump(model, fh, indent=2, sort_keys=True)
        fh.write("\n")

    def arr(name, values):
        rendered = ", ".join(f"{float(v):.17g}" for v in values)
        return f"inline constexpr std::array<double, FEATURE_COUNT> {name} = {{{rendered}}};\n"
    with open(args.header, "w") as fh:
        fh.write("// Generated by tools/policy_research/export_linear_qe.py.\n")
        fh.write("// Training corpus: game-paired-v1 + game-paired-v2; fixed lambda=2.\n")
        fh.write("#ifndef POLICY_RESEARCH_QE_MODEL_H_INCLUDED\n")
        fh.write("#define POLICY_RESEARCH_QE_MODEL_H_INCLUDED\n\n")
        fh.write("#include <array>\n#include <cstddef>\n\nnamespace Stockfish::Research::QEModel {\n")
        fh.write(f"inline constexpr std::size_t FEATURE_COUNT = {len(NUM_FEATURES)};\n")
        fh.write(f"inline constexpr double LAMBDA = {args.lambda_:.17g};\n")
        fh.write(arr("P1", p1)); fh.write(arr("P99", p99))
        fh.write(arr("MEAN", mu)); fh.write(arr("SD", sd))
        fh.write(arr("Q_COEF", wq)); fh.write(arr("COST_COEF", wc))
        fh.write(f"inline constexpr double Q_INTERCEPT = {bq:.17g};\n")
        fh.write(f"inline constexpr double COST_INTERCEPT = {bc:.17g};\n")
        fh.write("}\n\n#endif\n")
    print(f"fit {len(rows)} rows / {len(examples)} candidate examples")
    print(f"wrote {args.json} and {args.header}")


if __name__ == "__main__":
    main()
